  import React, { useId } from 'react'

  
  function InputBox({
    label, //"to" or "from" box
    amount, 
    onAmountChange, //function to handle the amount change
    onCurrencyChange, //function to handle the currency change
    currencyOptions = [],  //array of currency options
    selectCurrency = "usd", //default currency
    amountDisable = false, //disable the amount input - not actually needed
    currencyDisable = false, //disable the currency input - not actually needed
    className = "", //class name for the input box
}) {
   
    const amountInputId = useId() //useId is a hook that generates a unique id for the input box

    return (
        <div className={`bg-white p-3 rounded-lg text-sm flex ${className}`}>
            <div className="w-1/2">
                <label htmlFor={amountInputId}  className="text-black/50 mb-2 inline-block">
                    {label}              
                </label>
                <input
                    id={amountInputId} //using the uniqueID generated by useId hook
                    className="outline-none w-full bg-transparent py-1.5 border-2 border-gray-300 rounded-md px-2"
                    type="number"
                    min='0'
                    placeholder="Amount"
                    disabled={amountDisable}
                    value={amount === 0 ? "0" : amount || ""} //this ensures amount can be empty as well
                    onChange={(e) => {
                        // onAmountChange && onAmountChange(Number(e.target.value))

                        const val = e.target.value === "" ? "" : Number(e.target.value);
                        onAmountChange && onAmountChange(val);
                    }}
                />
            </div>
            <div className="w-1/2 flex flex-wrap justify-end text-right">
                <p className="text-black/50 mb-2 w-full">Currency Type</p>
                <select
                    className="rounded-lg px-1 py-1 bg-gray-100 cursor-pointer outline-none"
                    value={selectCurrency} //default value
                    onChange={(e) => onCurrencyChange && onCurrencyChange(e.target.value)}
                    disabled={currencyDisable}
                >
                    {/* currencyOptions is an array of currency options */}
                        {currencyOptions.map((currency) => (
                            <option key={currency} value={currency}>  {/* // key is important in loops in react to improve performance */}
                            {currency}
                            </option>
                        ))}
                
                </select>
            </div>
        </div>
    );
}

export default InputBox;